# Generated by Django 4.0 on 2023-01-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(max_length=12)),
                ('documento', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=90)),
                ('apellidos', models.CharField(max_length=90)),
                ('hobbie', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
